import { ArrowLeft, ArrowRight, ArrowUpDown, Columns3, ListFilter, X } from "lucide-react";
import type { DatabaseColumnProjection, DatabaseFilter, DatabaseFilterGroup, DatabaseFilterOperator, DatabaseProjection, DatabaseProperty } from "@interactive-os/json-document-editing";
interface Props { readonly projection: DatabaseProjection; readonly properties: ReadonlyArray<DatabaseProperty>; readonly disabled: boolean; readonly onChange: (projection: DatabaseProjection) => void; readonly filter?: boolean; readonly sort?: boolean; readonly group?: boolean; readonly columns?: boolean; }
export function DatabaseViewControls({ projection, properties, disabled, onChange, filter = true, sort = true, group = true, columns = true }: Props) {
  const ids = properties.map((property) => property.id); const change = (next: Partial<DatabaseProjection>) => onChange({ search: next.search ?? projection.search, filter: next.filter ?? projection.filter, sorts: next.sorts ?? projection.sorts, groups: next.groups ?? projection.groups, columns: next.columns ?? projection.columns });
  return <>{filter ? <FilterBuilder value={projection.filter} propertyIds={ids} disabled={disabled} onChange={(value) => change({ filter: value })} /> : null}{sort ? <SortBuilder value={projection.sorts} propertyIds={ids} disabled={disabled} onChange={(value) => change({ sorts: value })} /> : null}{group ? <GroupBuilder propertyId={projection.groups[0]?.propertyId ?? ""} propertyIds={ids} disabled={disabled} onChange={(propertyId) => change({ groups: propertyId ? [{ propertyId, direction: "ascending" }] : [] })} /> : null}{columns ? <ColumnBuilder columns={projection.columns} disabled={disabled} onChange={(value) => change({ columns: value })} /> : null}</>;
}
function FilterBuilder(props: { readonly value: DatabaseFilterGroup; readonly propertyIds: ReadonlyArray<string>; readonly disabled: boolean; readonly onChange: (value: DatabaseFilterGroup) => void }) {
  const rules = props.value.items.filter((item): item is DatabaseFilter => typeof item.propertyId === "string");
  return <details><summary aria-label="Filter" title="Filter"><ListFilter aria-hidden="true" size={16} />{rules.length ? <small>{rules.length}</small> : null}</summary><div className="jd-database__column-menu"><label>Match <select disabled={props.disabled} value={props.value.conjunction} onChange={(event) => props.onChange({ ...props.value, conjunction: event.currentTarget.value as "and" | "or" })}><option value="and">all</option><option value="or">any</option></select></label>{rules.map((rule) => <div key={rule.id} className="jd-database__control-row"><select aria-label="Filter property" disabled={props.disabled} value={rule.propertyId} onChange={(event) => props.onChange(replaceRule(props.value, { ...rule, propertyId: event.currentTarget.value }))}>{props.propertyIds.map((id) => <option key={id}>{id}</option>)}</select><select aria-label="Filter operator" disabled={props.disabled} value={rule.operator} onChange={(event) => props.onChange(replaceRule(props.value, { ...rule, operator: event.currentTarget.value as DatabaseFilterOperator }))}>{["equals", "not-equals", "contains", "greater-than", "less-than", "is-empty"].map((operator) => <option key={operator}>{operator}</option>)}</select>{rule.operator !== "is-empty" ? <input aria-label="Filter value" disabled={props.disabled} value={String(rule.value)} onChange={(event) => props.onChange(replaceRule(props.value, { ...rule, value: event.currentTarget.value }))} /> : null}<button type="button" aria-label="Remove filter" onClick={() => props.onChange({ ...props.value, items: props.value.items.filter((item) => item.id !== rule.id) })}><X aria-hidden="true" size={16} /></button></div>)}<button type="button" disabled={props.disabled || props.propertyIds.length === 0} onClick={() => props.onChange({ ...props.value, items: [...props.value.items, { id: crypto.randomUUID(), propertyId: props.propertyIds[0]!, operator: "equals", value: "" }] })}>Add filter</button></div></details>;
}
function SortBuilder(props: { readonly value: DatabaseProjection["sorts"]; readonly propertyIds: ReadonlyArray<string>; readonly disabled: boolean; readonly onChange: (value: DatabaseProjection["sorts"]) => void }) { return <details><summary aria-label="Sort" title="Sort"><ArrowUpDown aria-hidden="true" size={16} />{props.value.length ? <small>{props.value.length}</small> : null}</summary><div className="jd-database__column-menu">{props.value.map((sort, index) => <div key={`${sort.propertyId}:${index}`} className="jd-database__control-row"><select aria-label={`Sort property ${index + 1}`} value={sort.propertyId} onChange={(event) => props.onChange(props.value.map((item, position) => position === index ? { ...item, propertyId: event.currentTarget.value } : item))}>{props.propertyIds.map((id) => <option key={id}>{id}</option>)}</select><select aria-label={`Sort direction ${index + 1}`} value={sort.direction} onChange={(event) => props.onChange(props.value.map((item, position) => position === index ? { ...item, direction: event.currentTarget.value as "ascending" | "descending" } : item))}><option value="ascending">ascending</option><option value="descending">descending</option></select><button type="button" aria-label={`Remove sort ${index + 1}`} onClick={() => props.onChange(props.value.filter((_, position) => position !== index))}><X aria-hidden="true" size={16} /></button></div>)}<button type="button" disabled={props.disabled || props.propertyIds.length === 0} onClick={() => props.onChange([...props.value, { propertyId: props.propertyIds[0]!, direction: "ascending" }])}>Add sort</button></div></details>; }
function GroupBuilder(props: { readonly propertyId: string; readonly propertyIds: ReadonlyArray<string>; readonly disabled: boolean; readonly onChange: (value: string) => void }) { return <label><span className="jd-database__sr-only">Group</span><select aria-label="Group property" disabled={props.disabled} value={props.propertyId} onChange={(event) => props.onChange(event.currentTarget.value)}><option value="">Group</option>{props.propertyIds.map((id) => <option key={id}>{id}</option>)}</select></label>; }
function ColumnBuilder(props: { readonly columns: ReadonlyArray<DatabaseColumnProjection>; readonly disabled: boolean; readonly onChange: (value: ReadonlyArray<DatabaseColumnProjection>) => void }) { return <details><summary aria-label="Columns" title="Columns"><Columns3 aria-hidden="true" size={16} /></summary><div className="jd-database__column-menu">{props.columns.map((column, index) => <div key={column.propertyId} className="jd-database__control-row"><label><input type="checkbox" checked={column.visible} disabled={props.disabled} onChange={(event) => props.onChange(props.columns.map((item) => item.propertyId === column.propertyId ? { ...item, visible: event.currentTarget.checked } : item))} />{column.propertyId}</label><input aria-label={`Width ${column.propertyId}`} type="number" min="80" max="600" value={column.width ?? 160} onChange={(event) => props.onChange(props.columns.map((item) => item.propertyId === column.propertyId ? { ...item, width: Number(event.currentTarget.value) } : item))} /><button type="button" disabled={index === 0} aria-label={`Move ${column.propertyId} left`} onClick={() => props.onChange(move(props.columns, index, index - 1))}><ArrowLeft aria-hidden="true" size={16} /></button><button type="button" disabled={index === props.columns.length - 1} aria-label={`Move ${column.propertyId} right`} onClick={() => props.onChange(move(props.columns, index, index + 1))}><ArrowRight aria-hidden="true" size={16} /></button><button type="button" aria-label={`Pin ${column.propertyId}`} onClick={() => props.onChange(props.columns.map((item) => item.propertyId === column.propertyId ? { ...item, pinned: item.pinned === null ? "start" : null } : item))}>{column.pinned ? "Unpin" : "Pin"}</button></div>)}</div></details>; }
function replaceRule(group: DatabaseFilterGroup, rule: DatabaseFilter): DatabaseFilterGroup { return { ...group, items: group.items.map((item) => item.id === rule.id ? rule : item) }; }
function move<Value>(values: ReadonlyArray<Value>, from: number, to: number): ReadonlyArray<Value> { const next = [...values]; const [value] = next.splice(from, 1); if (value !== undefined) next.splice(to, 0, value); return next; }
