/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as PageRouteImport } from "./routes/_page";
import { Route as PageConnectorsIndexRouteImport } from "./routes/_page/connectors/index";
import { Route as PageConnectorsReactRouteImport } from "./routes/_page/connectors/react";
import { Route as PageConnectorsReactHookFormRouteImport } from "./routes/_page/connectors/react-hook-form";
import { Route as PageConnectorsTanstackTableRouteImport } from "./routes/_page/connectors/tanstack-table";
import { Route as PageConnectorsWebRouteImport } from "./routes/_page/connectors/web";
import { Route as PageDemoIndexRouteImport } from "./routes/_page/demo/index";
import { Route as PageDemoDatabaseRouteImport } from "./routes/_page/demo/database";
import { Route as PageDemoSelectionRouteImport } from "./routes/_page/demo/selection";
import { Route as PageDemoSheetRouteImport } from "./routes/_page/demo/sheet";
import { Route as PageDocsIndexRouteImport } from "./routes/_page/docs/index";
import { Route as PageDocsApiRouteImport } from "./routes/_page/docs/api";
import { Route as PageDocsConnectorsRouteImport } from "./routes/_page/docs/connectors";
import { Route as PageDocsTutorialRouteImport } from "./routes/_page/docs/tutorial";
import { Route as PageExamplesDocumentRouteImport } from "./routes/_page/examples/document";
import { Route as PageConnectorsZodIndexRouteImport } from "./routes/_page/connectors/zod/index";
import { Route as PageConnectorsZodValidateRouteImport } from "./routes/_page/connectors/zod/validate";

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const PageRoute = PageRouteImport.update({
  id: "/_page",
  getParentRoute: () => rootRouteImport,
} as any);
const PageConnectorsIndexRoute = PageConnectorsIndexRouteImport.update({
  id: "/connectors/",
  path: "/connectors/",
  getParentRoute: () => PageRoute,
} as any);
const PageConnectorsReactRoute = PageConnectorsReactRouteImport.update({
  id: "/connectors/react",
  path: "/connectors/react",
  getParentRoute: () => PageRoute,
} as any);
const PageConnectorsReactHookFormRoute =
  PageConnectorsReactHookFormRouteImport.update({
    id: "/connectors/react-hook-form",
    path: "/connectors/react-hook-form",
    getParentRoute: () => PageRoute,
  } as any);
const PageConnectorsTanstackTableRoute =
  PageConnectorsTanstackTableRouteImport.update({
    id: "/connectors/tanstack-table",
    path: "/connectors/tanstack-table",
    getParentRoute: () => PageRoute,
  } as any);
const PageConnectorsWebRoute = PageConnectorsWebRouteImport.update({
  id: "/connectors/web",
  path: "/connectors/web",
  getParentRoute: () => PageRoute,
} as any);
const PageDemoIndexRoute = PageDemoIndexRouteImport.update({
  id: "/demo/",
  path: "/demo/",
  getParentRoute: () => PageRoute,
} as any);
const PageDemoDatabaseRoute = PageDemoDatabaseRouteImport.update({
  id: "/demo/database",
  path: "/demo/database",
  getParentRoute: () => PageRoute,
} as any);
const PageDemoSelectionRoute = PageDemoSelectionRouteImport.update({
  id: "/demo/selection",
  path: "/demo/selection",
  getParentRoute: () => PageRoute,
} as any);
const PageDemoSheetRoute = PageDemoSheetRouteImport.update({
  id: "/demo/sheet",
  path: "/demo/sheet",
  getParentRoute: () => PageRoute,
} as any);
const PageDocsIndexRoute = PageDocsIndexRouteImport.update({
  id: "/docs/",
  path: "/docs/",
  getParentRoute: () => PageRoute,
} as any);
const PageDocsApiRoute = PageDocsApiRouteImport.update({
  id: "/docs/api",
  path: "/docs/api",
  getParentRoute: () => PageRoute,
} as any);
const PageDocsConnectorsRoute = PageDocsConnectorsRouteImport.update({
  id: "/docs/connectors",
  path: "/docs/connectors",
  getParentRoute: () => PageRoute,
} as any);
const PageDocsTutorialRoute = PageDocsTutorialRouteImport.update({
  id: "/docs/tutorial",
  path: "/docs/tutorial",
  getParentRoute: () => PageRoute,
} as any);
const PageExamplesDocumentRoute = PageExamplesDocumentRouteImport.update({
  id: "/examples/document",
  path: "/examples/document",
  getParentRoute: () => PageRoute,
} as any);
const PageConnectorsZodIndexRoute = PageConnectorsZodIndexRouteImport.update({
  id: "/connectors/zod/",
  path: "/connectors/zod/",
  getParentRoute: () => PageRoute,
} as any);
const PageConnectorsZodValidateRoute =
  PageConnectorsZodValidateRouteImport.update({
    id: "/connectors/zod/validate",
    path: "/connectors/zod/validate",
    getParentRoute: () => PageRoute,
  } as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/connectors/react": typeof PageConnectorsReactRoute;
  "/connectors/react-hook-form": typeof PageConnectorsReactHookFormRoute;
  "/connectors/tanstack-table": typeof PageConnectorsTanstackTableRoute;
  "/connectors/web": typeof PageConnectorsWebRoute;
  "/demo/database": typeof PageDemoDatabaseRoute;
  "/demo/selection": typeof PageDemoSelectionRoute;
  "/demo/sheet": typeof PageDemoSheetRoute;
  "/docs/api": typeof PageDocsApiRoute;
  "/docs/connectors": typeof PageDocsConnectorsRoute;
  "/docs/tutorial": typeof PageDocsTutorialRoute;
  "/examples/document": typeof PageExamplesDocumentRoute;
  "/connectors/": typeof PageConnectorsIndexRoute;
  "/demo/": typeof PageDemoIndexRoute;
  "/docs/": typeof PageDocsIndexRoute;
  "/connectors/zod/validate": typeof PageConnectorsZodValidateRoute;
  "/connectors/zod/": typeof PageConnectorsZodIndexRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/connectors/react": typeof PageConnectorsReactRoute;
  "/connectors/react-hook-form": typeof PageConnectorsReactHookFormRoute;
  "/connectors/tanstack-table": typeof PageConnectorsTanstackTableRoute;
  "/connectors/web": typeof PageConnectorsWebRoute;
  "/demo/database": typeof PageDemoDatabaseRoute;
  "/demo/selection": typeof PageDemoSelectionRoute;
  "/demo/sheet": typeof PageDemoSheetRoute;
  "/docs/api": typeof PageDocsApiRoute;
  "/docs/connectors": typeof PageDocsConnectorsRoute;
  "/docs/tutorial": typeof PageDocsTutorialRoute;
  "/examples/document": typeof PageExamplesDocumentRoute;
  "/connectors": typeof PageConnectorsIndexRoute;
  "/demo": typeof PageDemoIndexRoute;
  "/docs": typeof PageDocsIndexRoute;
  "/connectors/zod/validate": typeof PageConnectorsZodValidateRoute;
  "/connectors/zod": typeof PageConnectorsZodIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/_page": typeof PageRouteWithChildren;
  "/_page/connectors/react": typeof PageConnectorsReactRoute;
  "/_page/connectors/react-hook-form": typeof PageConnectorsReactHookFormRoute;
  "/_page/connectors/tanstack-table": typeof PageConnectorsTanstackTableRoute;
  "/_page/connectors/web": typeof PageConnectorsWebRoute;
  "/_page/demo/database": typeof PageDemoDatabaseRoute;
  "/_page/demo/selection": typeof PageDemoSelectionRoute;
  "/_page/demo/sheet": typeof PageDemoSheetRoute;
  "/_page/docs/api": typeof PageDocsApiRoute;
  "/_page/docs/connectors": typeof PageDocsConnectorsRoute;
  "/_page/docs/tutorial": typeof PageDocsTutorialRoute;
  "/_page/examples/document": typeof PageExamplesDocumentRoute;
  "/_page/connectors/": typeof PageConnectorsIndexRoute;
  "/_page/demo/": typeof PageDemoIndexRoute;
  "/_page/docs/": typeof PageDocsIndexRoute;
  "/_page/connectors/zod/validate": typeof PageConnectorsZodValidateRoute;
  "/_page/connectors/zod/": typeof PageConnectorsZodIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/connectors/react"
    | "/connectors/react-hook-form"
    | "/connectors/tanstack-table"
    | "/connectors/web"
    | "/demo/database"
    | "/demo/selection"
    | "/demo/sheet"
    | "/docs/api"
    | "/docs/connectors"
    | "/docs/tutorial"
    | "/examples/document"
    | "/connectors/"
    | "/demo/"
    | "/docs/"
    | "/connectors/zod/validate"
    | "/connectors/zod/";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/connectors/react"
    | "/connectors/react-hook-form"
    | "/connectors/tanstack-table"
    | "/connectors/web"
    | "/demo/database"
    | "/demo/selection"
    | "/demo/sheet"
    | "/docs/api"
    | "/docs/connectors"
    | "/docs/tutorial"
    | "/examples/document"
    | "/connectors"
    | "/demo"
    | "/docs"
    | "/connectors/zod/validate"
    | "/connectors/zod";
  id:
    | "__root__"
    | "/"
    | "/_page"
    | "/_page/connectors/react"
    | "/_page/connectors/react-hook-form"
    | "/_page/connectors/tanstack-table"
    | "/_page/connectors/web"
    | "/_page/demo/database"
    | "/_page/demo/selection"
    | "/_page/demo/sheet"
    | "/_page/docs/api"
    | "/_page/docs/connectors"
    | "/_page/docs/tutorial"
    | "/_page/examples/document"
    | "/_page/connectors/"
    | "/_page/demo/"
    | "/_page/docs/"
    | "/_page/connectors/zod/validate"
    | "/_page/connectors/zod/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  PageRoute: typeof PageRouteWithChildren;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_page": {
      id: "/_page";
      path: "";
      fullPath: "/";
      preLoaderRoute: typeof PageRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_page/connectors/": {
      id: "/_page/connectors/";
      path: "/connectors";
      fullPath: "/connectors/";
      preLoaderRoute: typeof PageConnectorsIndexRouteImport;
      parentRoute: typeof PageRoute;
    };
    "/_page/connectors/react": {
      id: "/_page/connectors/react";
      path: "/connectors/react";
      fullPath: "/connectors/react";
      preLoaderRoute: typeof PageConnectorsReactRouteImport;
      parentRoute: typeof PageRoute;
    };
    "/_page/connectors/react-hook-form": {
      id: "/_page/connectors/react-hook-form";
      path: "/connectors/react-hook-form";
      fullPath: "/connectors/react-hook-form";
      preLoaderRoute: typeof PageConnectorsReactHookFormRouteImport;
      parentRoute: typeof PageRoute;
    };
    "/_page/connectors/tanstack-table": {
      id: "/_page/connectors/tanstack-table";
      path: "/connectors/tanstack-table";
      fullPath: "/connectors/tanstack-table";
      preLoaderRoute: typeof PageConnectorsTanstackTableRouteImport;
      parentRoute: typeof PageRoute;
    };
    "/_page/connectors/web": {
      id: "/_page/connectors/web";
      path: "/connectors/web";
      fullPath: "/connectors/web";
      preLoaderRoute: typeof PageConnectorsWebRouteImport;
      parentRoute: typeof PageRoute;
    };
    "/_page/demo/": {
      id: "/_page/demo/";
      path: "/demo";
      fullPath: "/demo/";
      preLoaderRoute: typeof PageDemoIndexRouteImport;
      parentRoute: typeof PageRoute;
    };
    "/_page/demo/database": {
      id: "/_page/demo/database";
      path: "/demo/database";
      fullPath: "/demo/database";
      preLoaderRoute: typeof PageDemoDatabaseRouteImport;
      parentRoute: typeof PageRoute;
    };
    "/_page/demo/selection": {
      id: "/_page/demo/selection";
      path: "/demo/selection";
      fullPath: "/demo/selection";
      preLoaderRoute: typeof PageDemoSelectionRouteImport;
      parentRoute: typeof PageRoute;
    };
    "/_page/demo/sheet": {
      id: "/_page/demo/sheet";
      path: "/demo/sheet";
      fullPath: "/demo/sheet";
      preLoaderRoute: typeof PageDemoSheetRouteImport;
      parentRoute: typeof PageRoute;
    };
    "/_page/docs/": {
      id: "/_page/docs/";
      path: "/docs";
      fullPath: "/docs/";
      preLoaderRoute: typeof PageDocsIndexRouteImport;
      parentRoute: typeof PageRoute;
    };
    "/_page/docs/api": {
      id: "/_page/docs/api";
      path: "/docs/api";
      fullPath: "/docs/api";
      preLoaderRoute: typeof PageDocsApiRouteImport;
      parentRoute: typeof PageRoute;
    };
    "/_page/docs/connectors": {
      id: "/_page/docs/connectors";
      path: "/docs/connectors";
      fullPath: "/docs/connectors";
      preLoaderRoute: typeof PageDocsConnectorsRouteImport;
      parentRoute: typeof PageRoute;
    };
    "/_page/docs/tutorial": {
      id: "/_page/docs/tutorial";
      path: "/docs/tutorial";
      fullPath: "/docs/tutorial";
      preLoaderRoute: typeof PageDocsTutorialRouteImport;
      parentRoute: typeof PageRoute;
    };
    "/_page/examples/document": {
      id: "/_page/examples/document";
      path: "/examples/document";
      fullPath: "/examples/document";
      preLoaderRoute: typeof PageExamplesDocumentRouteImport;
      parentRoute: typeof PageRoute;
    };
    "/_page/connectors/zod/": {
      id: "/_page/connectors/zod/";
      path: "/connectors/zod";
      fullPath: "/connectors/zod/";
      preLoaderRoute: typeof PageConnectorsZodIndexRouteImport;
      parentRoute: typeof PageRoute;
    };
    "/_page/connectors/zod/validate": {
      id: "/_page/connectors/zod/validate";
      path: "/connectors/zod/validate";
      fullPath: "/connectors/zod/validate";
      preLoaderRoute: typeof PageConnectorsZodValidateRouteImport;
      parentRoute: typeof PageRoute;
    };
  }
}

interface PageRouteChildren {
  PageConnectorsReactRoute: typeof PageConnectorsReactRoute;
  PageConnectorsReactHookFormRoute: typeof PageConnectorsReactHookFormRoute;
  PageConnectorsTanstackTableRoute: typeof PageConnectorsTanstackTableRoute;
  PageConnectorsWebRoute: typeof PageConnectorsWebRoute;
  PageDemoDatabaseRoute: typeof PageDemoDatabaseRoute;
  PageDemoSelectionRoute: typeof PageDemoSelectionRoute;
  PageDemoSheetRoute: typeof PageDemoSheetRoute;
  PageDocsApiRoute: typeof PageDocsApiRoute;
  PageDocsConnectorsRoute: typeof PageDocsConnectorsRoute;
  PageDocsTutorialRoute: typeof PageDocsTutorialRoute;
  PageExamplesDocumentRoute: typeof PageExamplesDocumentRoute;
  PageConnectorsIndexRoute: typeof PageConnectorsIndexRoute;
  PageDemoIndexRoute: typeof PageDemoIndexRoute;
  PageDocsIndexRoute: typeof PageDocsIndexRoute;
  PageConnectorsZodValidateRoute: typeof PageConnectorsZodValidateRoute;
  PageConnectorsZodIndexRoute: typeof PageConnectorsZodIndexRoute;
}

const PageRouteChildren: PageRouteChildren = {
  PageConnectorsReactRoute: PageConnectorsReactRoute,
  PageConnectorsReactHookFormRoute: PageConnectorsReactHookFormRoute,
  PageConnectorsTanstackTableRoute: PageConnectorsTanstackTableRoute,
  PageConnectorsWebRoute: PageConnectorsWebRoute,
  PageDemoDatabaseRoute: PageDemoDatabaseRoute,
  PageDemoSelectionRoute: PageDemoSelectionRoute,
  PageDemoSheetRoute: PageDemoSheetRoute,
  PageDocsApiRoute: PageDocsApiRoute,
  PageDocsConnectorsRoute: PageDocsConnectorsRoute,
  PageDocsTutorialRoute: PageDocsTutorialRoute,
  PageExamplesDocumentRoute: PageExamplesDocumentRoute,
  PageConnectorsIndexRoute: PageConnectorsIndexRoute,
  PageDemoIndexRoute: PageDemoIndexRoute,
  PageDocsIndexRoute: PageDocsIndexRoute,
  PageConnectorsZodValidateRoute: PageConnectorsZodValidateRoute,
  PageConnectorsZodIndexRoute: PageConnectorsZodIndexRoute,
};

const PageRouteWithChildren = PageRoute._addFileChildren(PageRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PageRoute: PageRouteWithChildren,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
