import { expect, test } from "@playwright/test";

test("workspace fills the viewport and view navigation preserves document and editing coordinates", async ({ page }) => {
  await page.goto("/demo/canvas");
  const svg = page.locator("[data-canvas-slide]");
  await expect(svg).toBeVisible();
  const bounds = await svg.boundingBox();
  const size = page.viewportSize()!;
  expect(bounds).toEqual({ x: 0, y: 0, ...size });
  await expect(page.getByRole("navigation", { name: "Site navigation" })).toHaveCount(0);
  const initial = await svg.getAttribute("viewBox");
  await page.getByRole("button", { name: "확대", exact: true }).click();
  await expect(svg).not.toHaveAttribute("viewBox", initial!);
  await expect(page.getByRole("button", { name: "실행 취소", exact: true })).toBeDisabled();
  await page.getByRole("button", { name: "화면 이동", exact: true }).click();
  const zoomed = await svg.getAttribute("viewBox");
  await page.mouse.move(200, 300); await page.mouse.down(); await page.mouse.move(300, 350); await page.mouse.up();
  await expect(svg).not.toHaveAttribute("viewBox", zoomed!);
  await expect(page.locator("[data-canvas-object]")).toHaveCount(0);
  await page.getByRole("button", { name: "선택", exact: true }).click();
  await svg.focus();
  const beforeSpace = await svg.getAttribute("viewBox");
  await page.keyboard.down("Space");
  await page.mouse.move(200, 300); await page.mouse.down(); await page.mouse.move(240, 330); await page.mouse.up();
  await page.keyboard.up("Space");
  await expect(svg).not.toHaveAttribute("viewBox", beforeSpace!);
  await expect(page.locator("[data-canvas-object]")).toHaveCount(0);
  const beforeWheel = await svg.getAttribute("viewBox");
  await page.mouse.wheel(0, 50);
  await expect(svg).not.toHaveAttribute("viewBox", beforeWheel!);
  await page.getByRole("button", { name: "사각형", exact: true }).click();
  const view = (await svg.getAttribute("viewBox"))!.split(" ").map(Number);
  await page.mouse.move(200, 300); await page.mouse.down(); await page.mouse.move(320, 380); await page.mouse.up();
  const object = page.locator("[data-canvas-object]");
  await expect(object).toHaveCount(1);
  expect(Number(await object.getAttribute("x"))).toBeCloseTo(view[0]! + 200 / size.width * view[2]!, 2);
  expect(Number(await object.getAttribute("y"))).toBeCloseTo(view[1]! + 300 / size.height * view[3]!, 2);
  await page.getByRole("button", { name: "전체 보기", exact: true }).click();
  await page.getByRole("button", { name: "실행 취소", exact: true }).click();
  await expect(object).toHaveCount(0);
  await page.setViewportSize({ width: 390, height: 844 });
  await expect.poll(async () => (await svg.boundingBox())?.width).toBe(390);
  expect((await svg.boundingBox())?.height).toBe(844);
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBe(390);
});

test("Canvas Application has a bottom toolbar and FigJam keys that respect text and chat focus", async ({ page }) => {
  await page.goto("/demo/canvas");
  await expect(page).toHaveURL(/\/applications\/canvas$/);
  const svg = page.locator("[data-canvas-slide]");
  const toolbar = page.getByRole("toolbar", { name: "Canvas tools" });
  await expect(svg).toBeVisible();
  const rect = await toolbar.boundingBox();
  expect(rect!.y + rect!.height).toBeCloseTo(page.viewportSize()!.height - 16, 0);
  await page.getByRole("button", { name: "사이트 메뉴", exact: true }).click();
  await expect(page.getByRole("group", { name: "Applications", exact: true }).getByRole("link", { name: "Canvas", exact: true })).toHaveAttribute("href", "/applications/canvas");
  await page.getByRole("dialog", { name: "사이트 메뉴", exact: true }).press("Escape");
  await svg.focus();
  for (const [key, tool] of [["r", "rectangle"], ["o", "ellipse"], ["s", "sticky-note"], ["m", "path"], ["Shift+t", "table"], ["t", "text"], ["v", "select"]]) {
    await page.keyboard.press(key!);
    await expect(svg).toHaveAttribute("data-tool", tool!);
  }
  await svg.dispatchEvent("keydown", { key: "Process", code: "KeyR", keyCode: 229, bubbles: true });
  await expect(svg).toHaveAttribute("data-canvas-mode", "rectangle");
  await expect(svg).toHaveCSS("cursor", "crosshair");
  await expect(page.getByRole("button", { name: "사각형", exact: true })).toHaveAttribute("aria-pressed", "true");
  await svg.dispatchEvent("keydown", { key: "ㅅ", code: "KeyT", bubbles: true });
  await expect(svg).toHaveCSS("cursor", "text");
  await page.keyboard.down("Space");
  await expect(page.getByRole("button", { name: "화면 이동", exact: true })).toHaveAttribute("aria-pressed", "true");
  await expect(page.getByRole("button", { name: "글자", exact: true })).toHaveAttribute("aria-pressed", "false");
  await expect(svg).toHaveCSS("cursor", "grab");
  await page.mouse.move(200, 250); await page.mouse.down();
  await expect(svg).toHaveCSS("cursor", "grabbing");
  await page.mouse.up(); await page.keyboard.up("Space");
  await expect(svg).toHaveCSS("cursor", "text");
  await expect(page.getByRole("button", { name: "글자", exact: true })).toHaveAttribute("aria-pressed", "true");
  await page.keyboard.press("h");
  await expect(page.getByRole("button", { name: "화면 이동", exact: true })).toHaveAttribute("aria-pressed", "true");
  await page.keyboard.press("Escape");
  await expect(page.getByRole("button", { name: "화면 이동", exact: true })).toHaveAttribute("aria-pressed", "false");
  await page.keyboard.press("r");
  await page.mouse.move(180, 200); await page.mouse.down(); await page.mouse.move(280, 260); await page.mouse.up();
  const beforeFit = await svg.getAttribute("viewBox");
  await page.keyboard.press("Shift+2");
  await expect(svg).not.toHaveAttribute("viewBox", beforeFit!);
  await page.keyboard.press("Shift+1");
  await expect(svg).toHaveAttribute("viewBox", beforeFit!);
  await page.keyboard.press("t"); await page.mouse.click(350, 300);
  const text = page.getByRole("textbox", { name: "Canvas text" });
  await text.pressSequentially("rstomv");
  await expect(text).toHaveValue("rstomv");
  await text.press("ControlOrMeta+Enter");
  const chat = page.getByRole("textbox", { name: "Canvas 편집 요청", exact: true });
  await chat.pressSequentially("rstomv");
  await expect(chat).toContainText("rstomv");
  await expect(svg).toHaveAttribute("data-tool", "select");
  await chat.press("ControlOrMeta+a"); await chat.press("Backspace");
  await page.getByRole("button", { name: "색상", exact: true }).click();
  const panel = await page.getByRole("dialog", { name: "색상", exact: true }).boundingBox();
  expect(panel!.y).toBeGreaterThanOrEqual(0);
  await expect(toolbar.getByRole("button", { name: "색상", exact: true })).toHaveCount(0);
  await page.getByRole("dialog", { name: "색상", exact: true }).press("Escape");
  await page.setViewportSize({ width: 390, height: 844 });
  const smallToolbar = await toolbar.boundingBox();
  const smallChat = await page.getByRole("complementary", { name: "Canvas 도우미" }).boundingBox();
  expect(smallChat!.y + smallChat!.height).toBeLessThan(smallToolbar!.y);
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBe(390);
});

test("Canvas Widget consumes the same physical keymap, tool state and cursor", async ({ page }) => {
  await page.goto("/widgets/canvas");
  const svg = page.locator("[data-canvas-slide]");
  await expect(svg).toBeVisible();
  await svg.dispatchEvent("keydown", { key: "Process", code: "KeyR", keyCode: 229, bubbles: true });
  await expect(svg).toHaveAttribute("data-tool", "rectangle");
  await expect(svg).toHaveCSS("cursor", "crosshair");
  await expect(page.getByRole("button", { name: "사각형", exact: true })).toHaveAttribute("aria-pressed", "true");
  await page.getByRole("button", { name: "글자", exact: true }).click();
  await expect(svg).toHaveCSS("cursor", "text");
});

test("Canvas API Usage exposes the application and canonical keyboard and toolbar sources", async ({ page }) => {
  await page.goto("/docs/api/canvas");
  await page.getByRole("region", { name: "Live demo: /applications/canvas", exact: true }).scrollIntoViewIfNeeded();
  const workbench = page.getByRole("region", { name: "Demo workbench" }).first();
  await workbench.getByRole("tab", { name: "CanvasApplication.tsx", exact: true }).click();
  await workbench.getByRole("tab", { name: "keyboard.ts", exact: true }).click();
  await expect(workbench.getByRole("tabpanel").locator("pre")).toContainText('keySource');
  await expect(workbench.getByRole("link", { name: "API Reference" })).toHaveAttribute("href", "/docs/api/web");
  await workbench.getByRole("tab", { name: "toolbar.tsx", exact: true }).click();
  await expect(workbench.getByRole("link", { name: "API Reference" })).toHaveAttribute("href", "/docs/api/ui-primitives-react");
});


test("selection exposes formatting near the object while hover alone does not", async ({ page }) => {
  await page.goto("/applications/canvas");
  const svg = page.locator("[data-canvas-slide]");
  await expect(svg).toBeVisible();
  await page.keyboard.press("r");
  await page.mouse.move(200, 250); await page.mouse.down(); await page.mouse.move(400, 360); await page.mouse.up();
  await page.keyboard.press("Escape");
  await page.mouse.move(600, 200);
  await expect(page.getByRole("toolbar", { name: "콘텐츠 서식" })).toHaveCount(0);
  const object = page.locator("[data-canvas-object]");
  await object.hover();
  await expect(page.getByRole("toolbar", { name: "콘텐츠 서식" })).toHaveCount(0);
  await object.click();
  const formatting = page.getByRole("toolbar", { name: "콘텐츠 서식" });
  await expect(formatting).toBeVisible();
  const objectBox = await object.boundingBox();
  const formatBox = await formatting.boundingBox();
  expect(formatBox!.y + formatBox!.height).toBeLessThan(objectBox!.y);
  await formatting.getByRole("button", { name: "색상", exact: true }).click();
  await page.getByRole("button", { name: "색상: 빨강", exact: true }).click();
  await expect(object).toHaveAttribute("aria-pressed", "true");
  await expect.poll(() => page.evaluate(() => JSON.parse(localStorage.getItem("json-document.canvas.v1")!).objects[0].color)).toBe("#ef4444");
  await page.getByRole("dialog", { name: "색상" }).press("Escape");
  await svg.focus(); await page.keyboard.press("ControlOrMeta+z");
  await expect.poll(() => page.evaluate(() => JSON.parse(localStorage.getItem("json-document.canvas.v1")!).objects[0].color)).not.toBe("#ef4444");
});
