import { expect, test } from "@playwright/test";

test("workspace fills the viewport and view navigation preserves document and editing coordinates", async ({ page }) => {
  await page.goto("/demo/canvas");
  const svg = page.locator("[data-canvas-slide]");
  await expect(svg).toBeVisible();
  const bounds = await svg.boundingBox();
  const size = page.viewportSize()!;
  expect(bounds).toEqual({ x: 0, y: 0, ...size });
  await expect(page.getByRole("navigation", { name: "Site navigation" })).toHaveCount(0);
  const initial = await svg.getAttribute("viewBox");
  await page.getByRole("button", { name: "확대", exact: true }).click();
  await expect(svg).not.toHaveAttribute("viewBox", initial!);
  await expect(page.getByRole("button", { name: "실행 취소", exact: true })).toBeDisabled();
  await page.getByRole("button", { name: "화면 이동", exact: true }).click();
  const zoomed = await svg.getAttribute("viewBox");
  await page.mouse.move(200, 300); await page.mouse.down(); await page.mouse.move(300, 350); await page.mouse.up();
  await expect(svg).not.toHaveAttribute("viewBox", zoomed!);
  await expect(page.locator("[data-canvas-object]")).toHaveCount(0);
  await page.getByRole("button", { name: "선택", exact: true }).click();
  await svg.focus();
  const beforeSpace = await svg.getAttribute("viewBox");
  await page.keyboard.down("Space");
  await page.mouse.move(200, 300); await page.mouse.down(); await page.mouse.move(240, 330); await page.mouse.up();
  await page.keyboard.up("Space");
  await expect(svg).not.toHaveAttribute("viewBox", beforeSpace!);
  await expect(page.locator("[data-canvas-object]")).toHaveCount(0);
  const beforeWheel = await svg.getAttribute("viewBox");
  await page.mouse.wheel(0, 50);
  await expect(svg).not.toHaveAttribute("viewBox", beforeWheel!);
  await page.getByRole("button", { name: "사각형", exact: true }).click();
  const view = (await svg.getAttribute("viewBox"))!.split(" ").map(Number);
  await page.mouse.move(200, 300); await page.mouse.down(); await page.mouse.move(320, 380); await page.mouse.up();
  const object = page.locator("[data-canvas-object]");
  await expect(object).toHaveCount(1);
  expect(Number(await object.getAttribute("x"))).toBeCloseTo(view[0]! + 200 / size.width * view[2]!, 2);
  expect(Number(await object.getAttribute("y"))).toBeCloseTo(view[1]! + 300 / size.height * view[3]!, 2);
  await page.getByRole("button", { name: "전체 보기", exact: true }).click();
  await page.getByRole("button", { name: "실행 취소", exact: true }).click();
  await expect(object).toHaveCount(0);
  await page.setViewportSize({ width: 390, height: 844 });
  await expect.poll(async () => (await svg.boundingBox())?.width).toBe(390);
  expect((await svg.boundingBox())?.height).toBe(844);
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBe(390);
});
