export const ui = {
  frame: {
    app: "bg-white font-sans text-stone-900 antialiased",
    page: "min-h-full bg-white",
    plainPage: "min-h-full bg-white",
    content: "mx-auto max-w-6xl",
    header: "border-b border-black/[0.06]",
    hero: "border-b border-black/[0.06] bg-transparent",
    navigation: "border-b border-black/[0.06] bg-white text-sm md:border-b-0 md:border-r",
    brand: "font-mono text-stone-950 no-underline hover:text-stone-600 md:border-b md:border-black/[0.06]",
  },
  text: {
    label: "text-xs font-medium text-stone-500",
    title: "text-3xl font-semibold tracking-[-0.025em] text-stone-950",
    heading: "text-base font-semibold text-stone-950",
    body: "text-sm leading-6 text-stone-600",
    meta: "text-xs leading-5 text-stone-500",
  },
  surface: {
    flat: "shadow-none",
    workspace: "rounded-[10px] border border-black/[0.08] bg-white",
    raised: "rounded-[10px] border border-black/[0.08] bg-white shadow-[0_1px_2px_rgba(24,24,27,0.04),0_12px_32px_rgba(24,24,27,0.06)]",
    overlay: "rounded-[10px] border border-black/[0.08] bg-white shadow-[0_2px_4px_rgba(24,24,27,0.06),0_20px_48px_rgba(24,24,27,0.10)]",
    inset: "rounded-[6px] border border-black/[0.06] bg-[#f1f1ee]",
    tableHead: "border-b border-black/[0.08] text-stone-700",
    tableCell: "border-b border-black/[0.05] text-stone-600",
    table: "border-collapse text-left",
    divider: "border-t border-black/[0.06]",
    sectionDivider: "border-t border-black/[0.06]",
    navigationRule: "border-l border-transparent",
    separator: "bg-black/[0.08]",
    gridHead: "border border-black/[0.07] bg-[#f1f1ee] text-stone-600",
    gridIndex: "border border-black/[0.07] bg-[#f7f7f5] text-stone-400",
    gridCell: "border border-black/[0.07] bg-white",
    documentBlock: "border-b border-black/[0.06] bg-transparent last:border-b-0",
    documentIndex: "border-0 border-r border-black/[0.06] bg-[#f7f7f5] text-stone-400",
    empty: "rounded-[6px] border border-dashed border-black/[0.12] bg-[#f1f1ee] text-stone-500",
  },
  action: {
    primary: "rounded-[6px] border border-black/[0.10] bg-white px-3 py-2 text-xs font-medium text-stone-950 no-underline shadow-[0_1px_2px_rgba(24,24,27,0.05),0_5px_14px_rgba(24,24,27,0.05)] hover:bg-[#fbfbfa] disabled:cursor-not-allowed disabled:opacity-35",
    secondary: "rounded-[6px] border border-transparent bg-transparent px-3 py-2 text-xs font-medium text-stone-700 no-underline hover:border-black/[0.06] hover:bg-white disabled:cursor-not-allowed disabled:opacity-35",
    toggle: "rounded-[6px] border border-black/[0.08] bg-white px-3 py-2 text-xs font-medium text-stone-700 aria-pressed:bg-[#e8e8e4] aria-pressed:text-stone-950 disabled:cursor-not-allowed disabled:opacity-35",
  },
  field: {
    control: "rounded-[6px] border border-black/[0.10] bg-white px-3 py-2 text-sm leading-6 text-stone-900 outline-none focus:border-black/30",
    seamless: "border-0 bg-transparent px-3 py-2 text-sm leading-6 text-stone-800 outline-none",
  },
  code: {
    inline: "rounded-[6px] bg-[#ecece8] px-1 py-0.5 font-mono text-[0.85em] text-stone-800",
    block: "rounded-[6px] border border-black/[0.06] bg-[#f1f1ee] p-3 font-mono text-xs leading-5 text-stone-800",
    json: "rounded-[6px] border border-black/[0.06] bg-[#f1f1ee] p-3 font-mono text-xs leading-5 text-stone-800",
  },
  state: {
    current: "border-b border-transparent text-stone-500 no-underline hover:text-stone-950 aria-[current=page]:border-stone-950 aria-[current=page]:font-medium aria-[current=page]:text-stone-950 md:border-b-0 md:border-l",
    selected: "data-[selected=true]:relative data-[selected=true]:border-stone-500 data-[selected=true]:bg-[#ecece8] data-[selected=true]:outline data-[selected=true]:outline-2 data-[selected=true]:-outline-offset-2 data-[selected=true]:outline-stone-700",
    focus: "outline-none focus-visible:ring-2 focus-visible:ring-stone-400/70",
    skipLink: "rounded-[6px] border border-black/[0.10] bg-white px-3 py-2 text-xs font-medium text-stone-950 shadow-[0_2px_4px_rgba(24,24,27,0.06),0_20px_48px_rgba(24,24,27,0.10)] focus:not-sr-only focus:fixed focus:left-3 focus:top-3",
    disabled: "disabled:cursor-not-allowed disabled:opacity-35",
  },
  home: {
    page: "min-h-full overflow-hidden bg-white",
    hero: "relative isolate mx-auto min-h-[52rem] max-w-[92rem] overflow-hidden bg-white lg:min-h-screen",
    copy: "relative z-10 flex min-h-[52rem] max-w-2xl flex-col justify-start px-6 pb-[22rem] pt-20 sm:justify-center sm:px-12 sm:pb-[20rem] sm:pt-16 lg:min-h-screen lg:max-w-[42rem] lg:px-16 lg:pb-20 xl:px-24",
    title: "m-0 font-mono text-4xl font-medium tracking-[-0.045em] text-stone-950 sm:text-5xl lg:text-6xl",
    statement: "mb-0 mt-7 text-3xl font-semibold leading-[1.08] tracking-[-0.045em] text-stone-950 sm:text-4xl lg:text-5xl",
    description: "mb-0 mt-5 max-w-lg text-base leading-7 text-stone-600 sm:text-lg",
    install: "rounded-[6px] border border-black/[0.06] bg-[#f1f1ee] px-3 py-2 font-mono text-xs leading-5 text-stone-800",
    artwork: "pointer-events-none absolute inset-0 z-0 m-0 overflow-hidden",
    artworkImage: "absolute bottom-0 right-0 h-auto w-[140vw] max-w-none translate-x-[18%] sm:w-[112vw] sm:translate-x-[14%] lg:w-[78vw] lg:translate-x-[8%]",
  },
} as const;

export function classes(...values: ReadonlyArray<string | false | null | undefined>): string {
  return values.filter(Boolean).join(" ");
}
