export const ui = {
  frame: {
    app: "bg-paper font-sans text-ink antialiased",
    page: "min-h-full bg-paper px-4 py-8 lg:px-8",
    content: "mx-auto max-w-6xl",
    header: "border-b border-pencil-light/60",
    hero: "border-b border-pencil-light/60 bg-transparent",
    navigation: "border-b border-pencil-light/60 bg-paper text-sm md:border-b-0 md:border-r",
    brand: "font-mono text-ink-strong no-underline hover:text-ink md:border-b md:border-pencil-light/60",
  },
  accent: {
    impact: {
      text: "text-impact-ink",
      stroke: "stroke-impact",
    },
  },
  text: {
    label: "text-xs font-medium text-ink",
    title: "text-3xl font-semibold tracking-[-0.025em] text-ink-strong",
    heading: "text-base font-semibold text-ink-strong",
    body: "text-sm leading-6 text-ink",
    meta: "text-xs leading-5 text-pencil",
  },
  pageHeader: {
    root: "mb-7 border-b border-pencil-light/60 pb-5",
    layout: "grid min-w-0 gap-4",
    layoutWithAside: "lg:grid-cols-[minmax(0,1fr)_24rem] lg:items-end",
    copy: "relative min-w-0",
    copyWithArtwork: "pr-32 sm:pr-52",
    artwork: "pointer-events-none absolute right-0 top-0 m-0 flex h-20 w-28 items-start justify-end overflow-hidden sm:h-24 sm:w-48",
    image: "block max-h-full max-w-full object-contain object-right-bottom",
    aside: "min-w-0",
  },
  surface: {
    flat: "shadow-none",
    workspace: "rounded-[10px] border border-pencil-light bg-paper",
    raised: "rounded-[10px] border border-pencil-light bg-paper shadow-[0_1px_2px_rgba(69,67,62,0.04),0_12px_32px_rgba(69,67,62,0.06)]",
    overlay: "rounded-[10px] border border-pencil-light bg-paper shadow-[0_2px_4px_rgba(69,67,62,0.06),0_20px_48px_rgba(69,67,62,0.10)]",
    inset: "rounded-[6px] border border-pencil-light bg-paper-warm",
    tableHead: "border-b border-pencil-light text-ink",
    tableCell: "border-b border-pencil-light/70 text-ink",
    table: "border-collapse text-left",
    divider: "border-t border-pencil-light/70",
    sectionDivider: "border-t border-pencil-light/70",
    navigationRule: "border-l border-transparent",
    separator: "bg-pencil-light",
    gridHead: "border border-pencil-light bg-paper-warm text-ink",
    gridIndex: "border border-pencil-light bg-paper-warm text-pencil",
    gridCell: "border border-pencil-light bg-paper",
    documentBlock: "border-b border-pencil-light/70 bg-transparent last:border-b-0",
    documentIndex: "border-0 border-r border-pencil-light bg-paper-warm text-pencil",
    empty: "rounded-[6px] border border-dashed border-pencil-light bg-paper-warm text-pencil",
  },
  action: {
    primary: "rounded-[6px] border border-pencil-light bg-paper px-3 py-2 text-xs font-medium text-ink-strong no-underline shadow-[0_1px_2px_rgba(69,67,62,0.05),0_5px_14px_rgba(69,67,62,0.05)] hover:border-pencil hover:bg-paper-warm focus-visible:border-impact focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-impact/25 disabled:cursor-not-allowed disabled:border-pencil-light/60 disabled:text-pencil",
    secondary: "rounded-[6px] border border-transparent bg-transparent px-3 py-2 text-xs font-medium text-ink no-underline hover:border-pencil-light hover:bg-paper-warm focus-visible:border-impact focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-impact/25 disabled:cursor-not-allowed disabled:text-pencil",
    toggle: "rounded-[6px] border border-pencil-light bg-paper px-3 py-2 text-xs font-medium text-ink no-underline hover:border-pencil focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-impact/25 aria-pressed:border-impact aria-pressed:bg-paper-warm aria-pressed:text-ink-strong aria-pressed:ring-1 aria-pressed:ring-impact disabled:cursor-not-allowed disabled:border-pencil-light/60 disabled:text-pencil",
  },
  field: {
    control: "rounded-[6px] border border-pencil-light bg-paper px-3 py-2 text-sm leading-6 text-ink-strong outline-none hover:border-pencil focus-visible:border-impact focus-visible:ring-2 focus-visible:ring-impact/25 disabled:cursor-not-allowed disabled:bg-paper-warm disabled:text-pencil",
    seamless: "border-0 bg-transparent px-3 py-2 text-sm leading-6 text-ink-strong outline-none focus-visible:bg-paper focus-visible:ring-2 focus-visible:ring-impact/25",
  },
  code: {
    inline: "rounded-[2px] border border-pencil-light bg-paper-warm px-1 py-0.5 font-mono text-[0.85em] text-ink-strong",
    install: "min-w-0 self-start rounded-[3px] border border-pencil-light bg-paper p-3 shadow-none",
    prompt: "text-impact-ink",
    block: {
      frame: "min-w-0 overflow-hidden rounded-[3px] border border-pencil-light bg-paper-warm shadow-none",
      header: "flex h-9 items-center border-b border-pencil-light bg-paper px-3 font-mono",
      label: "text-[11px] font-medium text-ink",
      meta: "text-[10px] text-pencil",
      signal: "text-[10px] font-medium text-impact-ink",
      viewport: {
        compact: "max-h-32",
        content: "max-h-none",
        standard: "min-h-24 max-h-64",
        tall: "max-h-[34rem]",
      },
      pre: "m-0 overflow-auto bg-paper-warm",
      code: "block min-w-max whitespace-normal py-3 font-mono text-[14px] leading-[1.65] text-ink",
      line: "grid min-h-[1.65em] grid-cols-[2.5rem_minmax(max-content,1fr)] px-2.5",
      lineNumber: "select-none border-r border-pencil-light pr-2.5 text-right text-[10px] text-pencil before:content-[attr(data-line-number)]",
      lineContent: "whitespace-pre pl-2.5 pr-3",
      token: {
        comment: "text-pencil",
        key: "font-medium text-ink-strong",
        keyword: "font-medium text-ink-strong",
        string: "text-sage",
        literal: "font-medium text-sage",
        punctuation: "text-pencil",
      },
    },
  },
  changeFlow: {
    root: "rounded-[6px] border border-pencil-light bg-paper-warm px-3 py-3",
    caption: "mb-3 flex flex-wrap items-baseline gap-x-3 gap-y-1",
    title: "text-xs font-semibold text-ink-strong",
    description: "text-xs leading-5 text-pencil",
    list: "m-0 grid list-none gap-0 p-0 sm:grid-flow-col sm:auto-cols-fr",
    step: "relative grid min-w-0 grid-cols-[1rem_minmax(0,1fr)] gap-2 pb-3 last:pb-0 sm:block sm:pb-0 sm:pr-3 sm:last:pr-0",
    connector: "absolute bottom-0 left-[0.4375rem] top-3 w-px bg-pencil-light sm:bottom-auto sm:left-2 sm:right-0 sm:top-[0.4375rem] sm:h-px sm:w-auto",
    marker: "relative z-10 mt-0.5 block h-3 w-3 rounded-full border-2 border-pencil bg-paper group-data-[status=complete]:border-ink group-data-[status=complete]:bg-ink group-data-[status=current]:border-impact group-data-[status=current]:bg-impact group-data-[status=current]:ring-4 group-data-[status=current]:ring-impact/15 sm:mt-0",
    copy: "grid min-w-0 gap-0.5 sm:mt-2.5",
    label: "text-[11px] font-semibold leading-4 text-ink-strong group-data-[status=pending]:text-pencil",
    detail: "min-w-0 break-words font-mono text-[10px] leading-4 text-pencil group-data-[status=current]:text-impact-ink",
  },
  state: {
    current: "border-b border-transparent text-pencil no-underline hover:text-ink-strong aria-[current=page]:border-impact aria-[current=page]:font-medium aria-[current=page]:text-ink-strong md:border-b-0 md:border-l",
    selected: "data-[selected=true]:relative data-[selected=true]:border-impact data-[selected=true]:bg-paper-warm data-[selected=true]:outline data-[selected=true]:outline-2 data-[selected=true]:-outline-offset-2 data-[selected=true]:outline-impact",
    focus: "outline-none focus-visible:ring-2 focus-visible:ring-impact/35",
    skipLink: "rounded-[6px] border border-pencil-light bg-paper px-3 py-2 text-xs font-medium text-ink-strong shadow-[0_2px_4px_rgba(69,67,62,0.06),0_20px_48px_rgba(69,67,62,0.10)] focus:not-sr-only focus:fixed focus:left-3 focus:top-3 focus-visible:ring-2 focus-visible:ring-impact/35",
    disabled: "disabled:cursor-not-allowed disabled:text-pencil",
  },
  workbench: {
    darkStrip: "rounded-[10px] border border-ink bg-ink-strong text-paper",
    darkLabel: "text-xs font-medium uppercase tracking-wide text-impact",
    darkMeta: "text-[10px] text-pencil-light",
    darkChip: "rounded-full border border-pencil text-xs text-paper-warm",
    tab: "rounded-[6px] border border-transparent text-sm text-ink aria-pressed:border-impact aria-pressed:bg-paper-warm aria-pressed:text-ink-strong",
    compactList: "rounded-[10px] border border-pencil-light bg-paper divide-y divide-pencil-light/70",
    sidebar: "rounded-[6px] border border-pencil-light bg-paper-warm lg:border-l lg:border-t-0",
    item: "rounded-[6px] border border-pencil-light bg-paper text-sm text-ink aria-pressed:border-impact aria-pressed:bg-paper-warm aria-pressed:ring-1 aria-pressed:ring-impact",
    itemStrong: "rounded-[6px] border border-pencil-light bg-paper text-sm text-ink aria-pressed:border-impact aria-pressed:bg-paper-warm aria-pressed:ring-2 aria-pressed:ring-impact",
    inspectorToggle: "bg-ink-strong text-xs font-medium text-paper",
    inspectorGrid: "bg-ink",
    inspectorCell: "bg-ink-strong text-paper-warm",
    inspectorLabel: "text-[9px] font-medium uppercase tracking-wider text-impact",
    canvas: "rounded-[10px] border border-pencil-light bg-paper-grid bg-[size:16px_16px]",
    canvasObject: "rounded-[6px] border-2 border-paper text-xs font-medium text-paper shadow-[0_1px_2px_rgba(69,67,62,0.12)] outline-none aria-pressed:ring-2 aria-pressed:ring-impact aria-pressed:ring-offset-2",
    marquee: "border border-impact bg-impact/10",
  },
  database: {
    toolbar: "rounded-[10px] border border-pencil-light bg-paper shadow-[0_1px_2px_rgba(69,67,62,0.04)]",
    table: "border-collapse bg-paper text-left text-sm",
    head: "border border-pencil-light bg-paper-warm text-xs font-medium text-ink",
    cell: "border border-pencil-light bg-paper text-sm text-ink-strong",
    rowAction: "border border-pencil-light bg-paper-warm text-pencil",
    type: "rounded-full border border-pencil-light bg-paper px-2 py-0.5 text-[10px] font-medium text-pencil",
    select: "rounded-[6px] border border-pencil-light bg-paper px-2 py-1 text-sm text-ink outline-none hover:border-pencil focus-visible:border-impact focus-visible:ring-2 focus-visible:ring-impact/25",
    checkbox: "h-4 w-4 accent-impact",
    lease: "rounded-[6px] border border-impact/40 bg-impact-soft px-2 py-1 text-xs text-impact-ink",
  },
  home: {
    page: "min-h-full overflow-hidden bg-paper",
    hero: "relative isolate mx-auto min-h-[52rem] max-w-[92rem] overflow-hidden bg-paper lg:min-h-screen",
    copy: "relative z-10 flex min-h-[52rem] max-w-2xl flex-col justify-start px-6 pb-[22rem] pt-20 sm:justify-center sm:px-12 sm:pb-[20rem] sm:pt-16 lg:min-h-screen lg:max-w-[42rem] lg:px-16 lg:pb-20 xl:px-24",
    logoHeading: "m-0 w-full max-w-[29rem] text-ink-strong",
    logo: "block h-auto w-full overflow-visible",
    statement: "mb-0 mt-8 text-2xl font-semibold leading-tight tracking-[-0.035em] text-ink-strong sm:text-3xl",
    description: "mb-0 mt-4 max-w-md text-base leading-7 text-ink",
    entry: "mt-8 flex flex-wrap items-center gap-x-5 gap-y-3",
    install: "font-mono text-xs leading-5 text-pencil",
    startLink: "text-sm font-medium text-ink-strong underline decoration-impact/50 underline-offset-4 hover:decoration-impact",
    artwork: "pointer-events-none absolute inset-0 z-0 m-0 overflow-hidden",
    artworkImage: "absolute bottom-0 right-0 h-auto w-[140vw] max-w-none translate-x-[18%] sm:w-[112vw] sm:translate-x-[14%] lg:w-[78vw] lg:translate-x-[8%]",
  },
} as const;

export function classes(...values: ReadonlyArray<string | false | null | undefined>): string {
  return values.filter(Boolean).join(" ");
}
