// Public recipes for shared UI primitives and patterns only.
// Page- or route-specific composition belongs beside its owning route.
export const ui = {
  frame: {
    app: "bg-paper font-sans text-ink antialiased",
    page: "min-h-full bg-paper px-page pb-8 pt-4 lg:px-page-wide",
    content: "mx-auto max-w-6xl",
    navigation: "bg-paper-warm text-sm",
    brand: "font-mono text-ink-strong no-underline hover:text-ink",
  },
  nav: {
    menu: "grid gap-3 px-3 pb-3 md:px-2",
    groupToggle: "px-2 py-1 text-[10px] font-medium uppercase tracking-[0.16em] text-ink hover:border-transparent hover:bg-transparent",
    chevron: "text-pencil",
    list: "grid content-start",
    panel: "hidden data-[open=true]:grid",
    item: "flex border-l-2 border-transparent px-2 py-1 text-sm text-ink no-underline hover:text-ink-strong md:px-3",
    child: "flex border-l-2 border-transparent py-1 pl-5 text-sm text-ink no-underline hover:text-ink-strong md:pl-6",
    current: "aria-[current=page]:border-impact aria-[current=page]:font-medium aria-[current=page]:text-ink-strong data-[branch=true]:text-ink-strong",
  },
  breadcrumb: {
    nav: "mb-3",
    list: "m-0 flex list-none flex-wrap items-center p-0 text-xs leading-5 text-pencil",
    item: "flex items-center",
    link: "text-pencil no-underline hover:text-ink-strong",
    current: "font-medium text-ink-strong",
    sep: "mx-1.5 text-pencil-light",
  },
  accent: {
    impact: {
      stroke: "stroke-impact",
    },
  },
  text: {
    label: "text-xs font-medium text-ink",
    title: "text-page-title font-semibold tracking-[-0.025em] text-ink-strong",
    heading: "text-base font-semibold text-ink-strong",
    section: "mt-6 text-lg font-semibold tracking-[-0.015em] text-ink-strong first:mt-0",
    body: "text-sm leading-6 text-ink",
    meta: "text-xs leading-5 text-pencil",
  },
  product: {
    frame: "rounded-[10px] bg-paper shadow-[0_1px_2px_rgba(69,67,62,0.04),0_16px_40px_rgba(69,67,62,0.08)]",
    toolbar: "flex flex-wrap items-center gap-1 border-b border-pencil-light/40 px-3 py-2",
    canvas: "p-3",
    panel: "border-t border-pencil-light/40 px-3 py-2",
  },
  pageHeader: {
    root: "mb-8",
    layout: "grid min-w-0 gap-4",
    layoutWithAside: "lg:grid-cols-[minmax(0,1fr)_24rem] lg:items-end",
    copy: "relative min-w-0 border-b border-pencil-light/40 pb-5",
    copyWithArtwork: "pr-32 sm:pr-52",
    artwork: "pointer-events-none absolute right-0 top-0 m-0 flex h-20 w-28 items-start justify-end overflow-hidden sm:h-24 sm:w-48",
    image: "block max-h-full max-w-full object-contain object-right-bottom",
    aside: "min-w-0",
  },
  surface: {
    workspace: "rounded-[10px]",
    raised: "rounded-[10px] bg-paper-warm",
    overlay: "rounded-[10px] bg-paper shadow-[0_2px_4px_rgba(69,67,62,0.06),0_20px_48px_rgba(69,67,62,0.10)]",
    inset: "rounded-[6px] bg-paper-warm",
    tableHead: "border-b border-pencil-light text-ink",
    tableCell: "border-b border-pencil-light/70 text-ink",
    table: "border-collapse text-left",
    navigationRule: "border-l border-transparent",
    separator: "bg-pencil-light/40",
    gridHead: "border border-pencil-light bg-paper-warm text-ink",
    gridIndex: "border border-pencil-light bg-paper-warm text-pencil",
    gridCell: "border border-pencil-light bg-paper",
    selectableBlock: "border border-transparent bg-paper px-3 py-2 text-left text-xs font-medium",
    previewSelected: "relative border-impact bg-paper-warm outline outline-2 -outline-offset-2 outline-impact",
    documentBlock: "border-b border-pencil-light/70 bg-transparent px-2 py-1.5 last:border-b-0",
    documentIndex: "rounded-none border-0 border-r border-pencil-light bg-paper-warm text-pencil shadow-none",
    empty: "rounded-[6px] border border-dashed border-pencil-light bg-paper-warm text-pencil",
    marquee: "rounded-[6px] border border-dashed border-impact/50 bg-impact/10",
  },
  interactive: {
    control: "cursor-pointer rounded-[6px] border px-3 py-2 text-xs font-medium outline-none transition-[background-color,border-color,color,box-shadow,transform] duration-150 active:translate-y-px focus-visible:border-impact focus-visible:ring-2 focus-visible:ring-impact/25 disabled:cursor-not-allowed disabled:translate-y-0 disabled:border-pencil-light/60 disabled:bg-transparent disabled:text-pencil disabled:shadow-none",
    action: {
      primary: "border-pencil bg-ink-strong text-paper shadow-[0_1px_2px_rgba(69,67,62,0.10),0_5px_14px_rgba(69,67,62,0.10)] hover:border-ink-strong hover:bg-ink",
      secondary: "border-pencil-light bg-paper text-ink shadow-[0_1px_2px_rgba(69,67,62,0.05)] hover:border-pencil hover:bg-paper-warm",
      danger: "border-impact/60 bg-paper text-impact-ink hover:border-impact hover:bg-impact-soft",
    },
    link: {
      prominent: "inline-flex cursor-pointer items-center gap-2 rounded-[6px] border border-pencil-light bg-paper px-3 py-2 text-xs font-medium text-ink-strong no-underline shadow-[0_1px_2px_rgba(69,67,62,0.05),0_5px_14px_rgba(69,67,62,0.05)] transition-[background-color,border-color,box-shadow,transform] duration-150 hover:border-pencil hover:bg-paper-warm active:translate-y-px focus-visible:border-impact focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-impact/25",
      quiet: "inline-flex cursor-pointer items-center text-ink-strong underline decoration-pencil-light underline-offset-4 transition-colors hover:decoration-impact focus-visible:rounded-[2px] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-impact/25",
    },
    toggle: "border-pencil-light bg-paper text-ink hover:border-pencil hover:bg-paper-warm aria-pressed:border-impact aria-pressed:bg-paper-warm aria-pressed:text-impact-ink aria-pressed:ring-1 aria-pressed:ring-impact disabled:aria-pressed:border-pencil-light/60 disabled:aria-pressed:bg-transparent disabled:aria-pressed:text-pencil disabled:aria-pressed:ring-0",
    disclosure: "group flex w-full cursor-pointer items-center justify-between gap-3 rounded-[6px] border border-transparent bg-transparent px-3 py-2 text-left text-sm font-medium text-ink-strong outline-none transition-colors hover:border-pencil-light hover:bg-paper-warm focus-visible:border-impact focus-visible:ring-2 focus-visible:ring-impact/25 disabled:cursor-not-allowed disabled:text-pencil",
    chevron: "text-pencil transition-transform group-aria-expanded:rotate-180",
    selectable: "cursor-pointer outline-none transition-[background-color,border-color,box-shadow] duration-150 hover:bg-paper-warm focus-visible:ring-2 focus-visible:ring-impact/25 focus-within:ring-2 focus-within:ring-impact/25 data-[selected=true]:relative data-[selected=true]:border-impact data-[selected=true]:bg-paper-warm data-[selected=true]:outline data-[selected=true]:outline-2 data-[selected=true]:-outline-offset-2 data-[selected=true]:outline-impact data-[focus=true]:outline data-[focus=true]:outline-2 data-[focus=true]:-outline-offset-1 data-[focus=true]:outline-ink",
    planeItem: "absolute !absolute grid place-items-center",
    icon: "flex h-7 w-7 cursor-pointer items-center justify-center rounded-[4px] border border-transparent bg-transparent text-pencil outline-none transition-colors hover:border-pencil-light hover:bg-paper hover:text-ink-strong active:bg-paper-warm focus-visible:border-impact focus-visible:ring-2 focus-visible:ring-impact/25 disabled:cursor-not-allowed disabled:border-transparent disabled:bg-transparent disabled:text-pencil-light",
    contextMenu: "absolute z-10 min-w-28 rounded-[6px] border border-pencil-light bg-paper py-1 shadow-[0_2px_4px_rgba(69,67,62,0.06),0_20px_48px_rgba(69,67,62,0.10)]",
    contextMenuItem: "block w-full px-3 py-1 text-left text-xs text-ink hover:bg-paper-warm",
  },
  field: {
    control: "rounded-[6px] border border-pencil-light bg-paper px-3 py-2 text-sm leading-6 text-ink-strong outline-none hover:border-pencil focus-visible:border-impact focus-visible:ring-2 focus-visible:ring-impact/25 disabled:cursor-not-allowed disabled:bg-paper-warm disabled:text-pencil",
    seamless: "border-0 bg-transparent px-3 py-2 text-sm leading-6 text-ink-strong outline-none focus-visible:bg-paper focus-visible:ring-2 focus-visible:ring-impact/25",
  },
  contenteditable: {
    canvas: "min-h-28 whitespace-pre-wrap rounded-[6px] border border-pencil bg-paper-warm px-4 py-3 text-base leading-7 text-ink-strong shadow-[inset_0_1px_2px_rgba(69,67,62,0.04)] outline-none transition-[background-color,border-color,box-shadow] hover:border-ink focus-visible:border-impact focus-visible:bg-paper focus-visible:ring-2 focus-visible:ring-impact/25",
  },
  code: {
    inline: "rounded-[2px] bg-paper-warm px-1 py-0.5 font-mono text-[0.85em] text-ink-strong",
    install: "min-w-0 self-start rounded-[3px] bg-paper-warm p-3 shadow-none",
    prompt: "text-impact-ink",
    block: {
      frame: "relative min-w-0 overflow-hidden rounded-[3px] bg-paper-warm shadow-none",
      copy: "absolute right-1.5 top-1.5 z-10 h-6 w-6 bg-paper-warm/90 data-[copied=true]:text-sage [&_path]:stroke-current [&_path]:stroke-2 [&_path]:[stroke-linecap:round] [&_path]:[stroke-linejoin:round] [&_rect]:stroke-current [&_rect]:stroke-2",
      viewport: {
        compact: "max-h-32",
        content: "max-h-none",
        standard: "min-h-24 max-h-64",
        tall: "max-h-[34rem]",
      },
      pre: "m-0 overflow-auto bg-paper-warm",
      code: "block min-w-max whitespace-normal py-2 font-mono text-[13px] leading-[1.55] text-ink",
      line: "grid min-h-[1.55em] grid-cols-[2.25rem_minmax(max-content,1fr)] px-2",
      lineNumber: "select-none pr-2 text-right text-[9px] text-pencil before:content-[attr(data-line-number)]",
      lineContent: "whitespace-pre pl-2 pr-10",
      token: {
        comment: "text-pencil",
        key: "font-medium text-ink-strong",
        keyword: "font-medium text-ink-strong",
        string: "text-sage",
        literal: "font-medium text-sage",
        punctuation: "text-pencil",
      },
    },
  },
  state: {
    focus: "outline-none focus-visible:ring-2 focus-visible:ring-impact/35",
    skipLink: "rounded-[6px] border border-pencil-light bg-paper px-3 py-2 text-xs font-medium text-ink-strong shadow-[0_2px_4px_rgba(69,67,62,0.06),0_20px_48px_rgba(69,67,62,0.10)] focus:not-sr-only focus:fixed focus:left-3 focus:top-3 focus-visible:ring-2 focus-visible:ring-impact/35",
    error: "text-impact-ink",
  },
  database: {
    toolbar: "rounded-[10px]",
    table: "border-collapse bg-paper text-left text-sm",
    head: "border border-pencil-light bg-paper-warm text-xs font-medium text-ink",
    cell: "border border-pencil-light bg-paper text-sm text-ink-strong",
    rowAction: "border border-pencil-light bg-paper-warm text-pencil",
    type: "rounded-full border border-pencil-light bg-paper px-2 py-0.5 text-[10px] font-medium text-pencil",
    select: "rounded-[6px] border border-pencil-light bg-paper px-2 py-1 text-sm text-ink outline-none hover:border-pencil focus-visible:border-impact focus-visible:ring-2 focus-visible:ring-impact/25",
    checkbox: "h-4 w-4 accent-impact",
    lease: "rounded-[6px] border border-impact/40 bg-impact-soft px-2 py-1 text-xs text-impact-ink",
  },
} as const;

export function classes(...values: ReadonlyArray<string | false | null | undefined>): string {
  return values.filter(Boolean).join(" ");
}
