import { tv } from "tailwind-variants";

export const uiPrimitivesCatalog = tv({
  slots: {
    catalog: "grid gap-20 pb-16",
    catalogIndex: "sticky top-0 z-20 flex flex-wrap gap-x-1 gap-y-1 border-y border-line-subtle bg-background-canvas/95 py-2 backdrop-blur",
    catalogIndexLink: "rounded-control px-3 py-1.5 text-xs text-foreground-muted no-underline hover:bg-background-subtle hover:text-foreground-strong focus-visible:outline focus-visible:outline-2 focus-visible:outline-line-accent",
    section: "grid gap-8 border-t border-line-subtle pt-12",
    sectionIntro: "max-w-2xl",
    sectionStage: "grid min-w-0 gap-8",
    controlGallery: "grid gap-6 lg:grid-cols-2",
    controlGroup: "grid min-w-0 content-start gap-5 rounded-surface bg-background-subtle/55 p-6 sm:p-8",
    controlWide: "lg:col-span-2",
    controlScenarioHeader: "flex flex-wrap items-center justify-between gap-3",
    controlScenarioTitle: "m-0 text-sm font-medium text-foreground-strong",
    controlToolbar: "flex flex-wrap items-center gap-3 border-t border-line-subtle pt-4",
    controlSettingsGrid: "grid gap-x-8 gap-y-6 md:grid-cols-2",
    controlSetting: "grid min-w-0 content-start gap-3 border-t border-line-subtle pt-4",
    controlSettingLabel: "m-0 text-overline uppercase text-foreground-muted",
    controlSplit: "grid gap-8 md:grid-cols-2",
    fieldCluster: "grid gap-2",
    compactSpecimen: "grid max-w-md gap-3",
    showroomGrid: "grid gap-6 lg:grid-cols-2",
    showroomWide: "overflow-hidden rounded-surface border border-line-subtle bg-background-canvas shadow-surface lg:col-span-2",
    showroomCard: "overflow-hidden rounded-surface border border-line-subtle bg-background-canvas shadow-surface",
    showroomBar: "flex min-h-16 items-center justify-between gap-4 border-b border-line-subtle px-5 py-3",
    showroomPath: "min-w-0 flex-1 truncate text-xs text-foreground-muted",
    showroomActions: "flex flex-wrap items-center justify-end gap-2",
    documentStage: "mx-auto grid min-h-80 max-w-3xl content-center gap-5 px-8 py-16 sm:px-14 lg:px-20 data-[mode=edit]:bg-background-subtle/40",
    eyebrow: "m-0 text-overline uppercase text-foreground-muted",
    showroomTitle: "m-0 max-w-2xl text-3xl font-semibold leading-tight tracking-tight text-foreground-strong sm:text-4xl",
    cardTitle: "m-0 text-lg font-semibold tracking-tight text-foreground-strong",
    detailTitle: "m-0 text-xl font-semibold tracking-tight text-foreground-strong",
    leadCopy: "m-0 max-w-2xl text-sm leading-6 text-foreground-default",
    bodyCopy: "m-0 text-xs leading-5 text-foreground-muted",
    inboxLayout: "grid min-h-80 sm:grid-cols-[minmax(10rem,0.8fr)_minmax(0,1.35fr)]",
    inboxList: "grid content-start border-b border-line-subtle p-2 sm:border-b-0 sm:border-r",
    inboxItem: "flex w-full items-center justify-between gap-3 rounded-control border-0 bg-transparent px-3 py-3 text-left text-xs text-foreground-default data-[selected=true]:bg-background-subtle data-[selected=true]:font-medium data-[selected=true]:text-foreground-strong [&_small]:font-normal [&_small]:text-foreground-muted",
    inboxDetail: "grid content-center gap-5 p-7 sm:p-9",
    agentStage: "grid min-h-64 content-center gap-5 bg-background-subtle/55 p-7 sm:p-9",
    agentDraft: "rounded-surface bg-background-canvas p-4 shadow-surface",
    composer: "grid grid-cols-[minmax(0,1fr)_auto_auto] items-center gap-3 border-t border-line-subtle p-4",
    composerField: "min-w-0 border-0 bg-transparent px-2 py-2 text-sm text-foreground-strong outline-none placeholder:text-foreground-muted",
    quietTrigger: "cursor-pointer border-0 bg-transparent px-2 py-2 text-xs text-foreground-muted outline-none hover:text-foreground-strong focus-visible:ring-2 focus-visible:ring-line-accent/25",
    row: "flex flex-wrap items-center gap-2",
    stack: "grid max-w-4xl gap-8",
    swatchGrid: "grid grid-cols-2 gap-x-5 gap-y-4 sm:grid-cols-3 lg:grid-cols-4",
    swatch: "grid gap-2",
    swatchChip: "h-9 rounded-control border border-line-subtle shadow-inset",
    typeRow: "grid gap-1 border-l-2 border-line-subtle pl-4",
    metricRow: "flex flex-wrap items-end gap-4",
    tokenDetails: "grid gap-8 border-t border-line-subtle pt-8 lg:grid-cols-[minmax(0,1.4fr)_minmax(0,0.8fr)_minmax(0,0.8fr)]",
    tokenDetail: "grid content-start gap-4",
    radiusBox: "grid h-14 w-14 place-items-center bg-background-subtle text-overline text-foreground-muted",
    shadowBox: "grid h-14 min-w-24 place-items-center bg-background-canvas px-3 text-overline text-foreground-muted",
    specimen: "grid gap-3 border-t border-line-subtle pt-4 first:border-t-0 first:pt-0",
    overlayGallery: "grid gap-6 lg:grid-cols-2",
    overlayScene: "grid min-h-52 content-start gap-5 rounded-surface bg-background-subtle/55 p-6 sm:p-8",
    overlay: "absolute z-10 mt-1 min-w-40 rounded-surface border border-line-subtle bg-background-canvas py-1 shadow-overlay",
    option: "block w-full px-3 py-1.5 text-left text-xs text-foreground-default hover:bg-background-subtle",
    optionFocused: "bg-background-subtle text-foreground-strong",
    optionSelected: "font-medium text-foreground-strong",
    trigger: "cursor-pointer rounded-control border border-line-subtle bg-background-canvas px-3 py-2 text-xs font-medium text-foreground-default outline-none hover:border-line-default hover:bg-background-subtle focus-visible:border-line-accent focus-visible:ring-2 focus-visible:ring-line-accent/25",
    menuRoot: "relative",
    drop: "grid min-h-24 place-items-center rounded-surface border border-dashed border-line-subtle bg-background-subtle p-4 data-[drop-active=true]:border-line-accent data-[drop-active=true]:bg-background-accent-subtle",
    dropOverlay: "pointer-events-none text-sm font-medium text-foreground-accent",
    gridTable: "w-full border-collapse bg-background-canvas text-left text-sm",
    gridHead: "border border-line-subtle bg-background-subtle px-3 py-2 text-xs font-medium text-foreground-default",
    gridCell: "border border-line-subtle bg-background-canvas px-3 py-2 text-sm text-foreground-strong data-[selected=true]:bg-background-subtle data-[selected=true]:outline data-[selected=true]:outline-2 data-[selected=true]:-outline-offset-2 data-[selected=true]:outline-line-accent data-[focus=true]:outline data-[focus=true]:outline-2 data-[focus=true]:-outline-offset-2 data-[focus=true]:outline-foreground-default",
    surfaceWorkspace: "grid overflow-hidden rounded-surface border border-line-subtle bg-background-canvas md:grid-cols-[14rem_minmax(0,1fr)]",
    surfaceSidebar: "grid content-start gap-5 border-b border-line-subtle bg-background-subtle/50 p-5 md:border-b-0 md:border-r",
    surfaceCanvas: "grid gap-6 p-5",
    handleStage: "relative min-h-56 overflow-hidden rounded-surface bg-background-canvas",
    surfacePanel: "absolute left-4 top-4 grid min-h-32 gap-3 border border-line-default bg-background-canvas p-3 shadow-surface",
    surfacePanelHeader: "flex items-center gap-2 border-b border-line-subtle pb-2",
    dragHandle: "border-0 bg-transparent p-1 text-foreground-muted",
    resizeHandle: "absolute inset-y-0 right-0 w-2 border-0 bg-line-accent/30 p-0",
    controlPlane: "relative h-12 border border-dashed border-line-subtle bg-background-subtle/40",
    controlHandle: "absolute h-4 w-4 -translate-x-1/2 -translate-y-1/2 rounded-full border border-background-canvas bg-line-accent p-0",
    motionGrid: "grid gap-x-6 gap-y-8 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4",
    motionStage: "flex min-h-24 items-center p-3",
    identity: "w-full rounded-surface bg-background-canvas px-4 py-3 text-foreground-strong",
    bar: "w-full",
    massFill: "h-24 w-full overflow-hidden rounded-surface",
    panel: "rounded-surface bg-background-subtle p-3",
    list: "m-0 grid list-none gap-1 p-0",
    selectionList: "m-0 grid max-w-sm list-none gap-1 rounded-surface bg-background-subtle p-1",
    selectionItem: "w-full rounded-control border-0 bg-transparent px-3 py-2 text-left text-xs text-foreground-default data-[selected=true]:bg-background-canvas data-[selected=true]:font-medium data-[selected=true]:text-foreground-strong data-[focus=true]:outline data-[focus=true]:outline-1 data-[focus=true]:outline-line-default",
    shellCanvas: "grid min-h-52 place-items-center bg-background-subtle/45 p-6",
    shellArtifact: "grid w-full max-w-md gap-3 rounded-surface bg-background-canvas p-6 shadow-surface",
    shellArtifactLine: "h-2 rounded-full bg-line-subtle",
    dateGroup: "grid gap-5 border-t border-line-subtle pt-7 first:border-t-0 first:pt-0 md:grid-cols-2",
    dateGroupTitle: "m-0 md:col-span-2",
    wide: "md:col-span-2 lg:col-span-3 xl:col-span-4",
  },
  variants: {
    featured: {
      true: {
        section: "border-t-0 pt-0",
        sectionIntro: "max-w-2xl",
      },
    },
  },
});

export const tokenColorClass = {
  "background-canvas": "bg-background-canvas",
  "background-subtle": "bg-background-subtle",
  "background-accent": "bg-background-accent",
  "background-accent-subtle": "bg-background-accent-subtle",
  "background-action-primary": "bg-background-action-primary",
  "background-action-primary-hovered": "bg-background-action-primary-hovered",
  "foreground-default": "bg-foreground-default",
  "foreground-strong": "bg-foreground-strong",
  "foreground-muted": "bg-foreground-muted",
  "foreground-disabled": "bg-foreground-disabled",
  "foreground-inverse": "bg-foreground-inverse",
  "foreground-accent": "bg-foreground-accent",
  "foreground-success": "bg-foreground-success",
  "line-subtle": "bg-line-subtle",
  "line-default": "bg-line-default",
  "line-accent": "bg-line-accent",
  "line-action-primary": "bg-line-action-primary",
} as const;

export const tokenRadiusClass = {
  tight: "rounded-tight",
  control: "rounded-control",
  surface: "rounded-surface",
} as const;

export const tokenShadowClass = {
  surface: "shadow-surface",
  overlay: "shadow-overlay",
  inset: "shadow-inset",
} as const;
