export type {
  ClipboardCopyOptions,
  ClipboardCopyError,
  ClipboardCopyOk,
  ClipboardCopyResult,
  ClipboardCutOk,
  ClipboardCutError,
  ClipboardCutOptions,
  ClipboardCutResult,
  ClipboardEmpty,
  ClipboardMutationOk,
  ClipboardPasteDiscriminatorMismatch,
  ClipboardPasteError,
  ClipboardPasteResult,
  ClipboardReadOk,
  ClipboardReadOptions,
  ClipboardReadResult,
  ClipboardState,
  ClipboardWriteOptions,
  ClipboardSource,
  JSONDocumentPasteOptions,
  JSONDocumentPasteTarget,
} from "../../domain/document/clipboard/contract.js";
