export const annotationDemoStyles = {
  canvasFrame: "min-w-0 overflow-auto rounded-surface border border-line-subtle bg-background-subtle",
  stage: "relative min-w-full",
  canvas: "block h-auto w-full touch-none outline-none focus-visible:ring-2 focus-visible:ring-line-accent/35",
  commentCard: "absolute z-10 grid w-60 gap-1.5 rounded-surface border border-line-subtle bg-background-canvas p-2.5 shadow-overlay",
  commentTailAboveLeft: "absolute -bottom-2 -right-2 size-4 rotate-45 border-b border-r border-line-subtle bg-background-canvas",
  commentTailAboveRight: "absolute -bottom-2 -left-2 size-4 rotate-45 border-b border-l border-line-subtle bg-background-canvas",
  commentTailBelowLeft: "absolute -right-2 -top-2 size-4 rotate-45 border-r border-t border-line-subtle bg-background-canvas",
  commentTailBelowRight: "absolute -left-2 -top-2 size-4 rotate-45 border-l border-t border-line-subtle bg-background-canvas",
  commentInput: "min-h-6 max-h-40 w-full resize-none overflow-y-auto [field-sizing:content] !border-0 !bg-transparent !p-0 !shadow-none focus-visible:!border-0 focus-visible:!ring-0",
  commentActions: "flex items-center justify-end gap-2",
  sendHint: "text-overline text-foreground-muted",
  sendButton: "h-7 w-7 p-0",
  threadList: "grid content-start gap-2 p-3",
  threadButton: "flex w-full cursor-pointer items-start gap-2 rounded-surface border border-line-subtle bg-background-canvas p-3 text-left outline-none hover:border-line-default focus-visible:ring-2 focus-visible:ring-line-accent/25 data-[selected=true]:border-line-accent data-[selected=true]:bg-background-subtle",
  threadBadge: "grid size-5 shrink-0 place-items-center rounded-full bg-background-accent text-overline font-semibold text-foreground-inverse",
  structuredOutput: "m-0 max-h-64 overflow-auto whitespace-pre-wrap p-3 font-mono text-xs",
  uploadControl: "inline-flex size-8 cursor-pointer items-center justify-center rounded-none border border-transparent bg-transparent text-foreground-muted hover:border-line-subtle hover:bg-background-canvas hover:text-foreground-strong focus-within:border-line-accent focus-within:ring-2 focus-within:ring-line-accent/25",
  toolButton: "h-8 w-8 p-0",
} as const;
