import { tv } from "tailwind-variants";

export const dateControlsDemoRecipe = tv({
  slots: {
    monthRoot: "min-w-[36rem] overflow-hidden rounded-surface border border-line-subtle",
    monthHeaderRow: "grid grid-cols-7 border-b border-line-subtle",
    monthHeader: "p-2 text-center text-xs text-foreground-muted",
    monthWeek: "relative grid grid-cols-7 border-b border-line-subtle last:border-b-0",
    monthDay: "relative min-h-24 border-r border-line-subtle p-1 last:border-r-0",
    monthOutside: "text-foreground-muted",
    monthDayNumber: "text-xs",
    monthToday: "font-semibold text-foreground-accent",
    monthEventContainer: "relative z-10 min-w-0",
    monthAllDayEvent: "w-full truncate rounded-control bg-background-accent px-1 text-left text-xs text-foreground-inverse",
    monthTimedEvent: "flex w-full gap-1 truncate px-1 text-left text-xs",
    monthEventTitle: "truncate",
    monthEventTime: "text-foreground-muted",
    monthMore: "text-xs text-foreground-muted",
    monthOverflow: "absolute inset-1 z-20 rounded-surface border border-line-subtle bg-background-canvas p-2 shadow-overlay",
    monthOverflowEvent: "mt-1",
    timeRoot: "min-w-[36rem] overflow-hidden rounded-surface border border-line-subtle",
    timeHeader: "grid border-b border-line-subtle",
    timeColumnHeader: "flex flex-col items-center p-1 text-xs",
    timeMeta: "text-xs text-foreground-muted",
    timeDayNumber: "text-sm",
    timeToday: "font-semibold text-foreground-accent",
    timeAllDayLabel: "p-1 text-right text-xs text-foreground-muted",
    timeAllDayCell: "min-h-8 border-l border-line-subtle",
    timeAllDayEventContainer: "relative z-10 mx-0.5 my-1",
    timeAllDayEvent: "w-full truncate rounded-control bg-background-accent px-1 text-left text-xs text-foreground-inverse",
    timeViewport: "grid",
    timeHourGutter: "relative overflow-hidden",
    timeViewportAnchor: "pointer-events-none absolute left-0 top-0",
    timeHourLabel: "absolute right-1 text-xs text-foreground-muted",
    timeCell: "relative overflow-hidden border-l border-line-subtle",
    timeSelectedSlot: "pointer-events-none absolute inset-x-0 bg-background-subtle",
    timeHourRule: "absolute inset-x-0 border-t border-line-subtle",
    timeNowLine: "pointer-events-none absolute inset-x-0 z-20 border-t border-line-accent",
    timeEventContainer: "absolute z-10",
    timeEvent: "flex h-full w-full flex-col overflow-hidden rounded-control bg-background-subtle px-1 text-left text-xs",
    timeEventTitle: "truncate",
  },
});
