import { pageDescriptor } from "../../app/page-descriptors";

const documentSources = import.meta.glob<string>(
  ["../../../../docs/public/*.md", "../../../../docs/api-reference/*.md", "../../../../packages/*/docs/*.md"],
  { query: "?raw", import: "default", eager: true },
);

function docPage(path: string) {
  const page = pageDescriptor(path);
  const source = documentSources[`../../../../${page.documentSource}`];
  if (source === undefined) throw new Error(`Documentation source is not registered: ${path}`);
  const included = (page.documentIncludes ?? []).map((path) => {
    const source = documentSources[`../../../../${path}`];
    if (source === undefined) throw new Error(`Documentation source is not registered: ${path}`);
    return source;
  });
  return { ...page, source: [...included, source].join("\n\n") };
}

export const docPages = {
  markdownApi: docPage("/docs/api/markdown"),
  markdownWebApi: docPage("/docs/api/markdown-web"),
  canvasApi: docPage("/docs/api/canvas"),
  objectDocumentApi: docPage("/docs/api/object-document"),
  calendarDocumentApi: docPage("/docs/api/calendar-document"),
  overview: docPage("/docs"),
  concepts: docPage("/docs/concepts"),
  foundation: docPage("/docs/foundation"),
  buildingBlocks: docPage("/docs/building-blocks"),
  editing: docPage("/docs/editing"),
  howWeBuild: docPage("/docs/how-we-build"),
  applications: docPage("/applications"),
  documentTypes: docPage("/docs/document-types"),
  adapters: docPage("/docs/adapters"),
  adapterKeyboard: docPage("/docs/adapter-keyboard"),
  adapterGridCell: docPage("/docs/adapter-grid-cell"),
  adapterInteraction: docPage("/docs/adapter-interaction"),
  adapterClipboard: docPage("/docs/adapter-clipboard"),
  adapterVirtualSelection: docPage("/docs/adapter-virtual-selection"),
  adapterContenteditable: docPage("/docs/adapter-contenteditable"),
  affordance: docPage("/docs/affordance"),
  uiPrimitives: docPage("/docs/ui-primitives"),
  animation: docPage("/docs/animation"),
  affordanceSelect: docPage("/docs/affordance/select"),
  affordanceFold: docPage("/docs/affordance/fold"),
  affordanceDrag: docPage("/docs/affordance/drag"),
  affordanceHistory: docPage("/docs/affordance/history"),
  affordanceFocus: docPage("/docs/affordance/focus"),
  affordanceCaret: docPage("/docs/affordance/caret"),
  affordanceTypeahead: docPage("/docs/affordance/typeahead"),
  affordanceActivate: docPage("/docs/affordance/activate"),
  affordanceCancel: docPage("/docs/affordance/cancel"),
  affordanceDelete: docPage("/docs/affordance/delete"),
  affordanceRename: docPage("/docs/affordance/rename"),
  affordanceNudge: docPage("/docs/affordance/nudge"),
  affordanceHover: docPage("/docs/affordance/hover"),
  affordanceContextual: docPage("/docs/affordance/contextual"),
  affordanceDoubleClick: docPage("/docs/affordance/double-click"),
  affordanceTripleClick: docPage("/docs/affordance/triple-click"),
  affordanceContextMenu: docPage("/docs/affordance/context-menu"),
  affordanceMarquee: docPage("/docs/affordance/marquee"),
  affordanceDrop: docPage("/docs/affordance/drop"),
  affordanceCopyDrag: docPage("/docs/affordance/copy-drag"),
  affordanceHandles: docPage("/docs/affordance/handles"),
  affordanceResize: docPage("/docs/affordance/resize"),
  affordancePan: docPage("/docs/affordance/pan"),
  affordanceScroll: docPage("/docs/affordance/scroll"),
  affordanceZoom: docPage("/docs/affordance/zoom"),
  affordanceSnap: docPage("/docs/affordance/snap"),
  affordanceForbid: docPage("/docs/affordance/forbid"),
  connectors: docPage("/docs/connectors"),
  connectorReact: docPage("/docs/connector-react"),
  connectorReactHookForm: docPage("/docs/connector-react-hook-form"),
  connectorAjv: docPage("/docs/connector-ajv"),
  connectorZod: docPage("/docs/connector-zod"),
  connectorZodValidate: docPage("/docs/connector-zod-validate"),
  connectorTanStackTable: docPage("/docs/connector-tanstack-table"),
  reactEditing: docPage("/docs/react-editing"),
  collaboration: docPage("/docs/collaboration"),
  collaborationReplica: docPage("/docs/collaboration/replica"),
  collaborationHistory: docPage("/docs/collaboration/history"),
  collaborationText: docPage("/docs/collaboration/text"),
  collaborationLease: docPage("/docs/collaboration/text/lease"),
  collaborationLifecycle: docPage("/docs/collaboration/lifecycle"),
  hands: docPage("/editors"),
  composer: docPage("/docs/composer"),
  mention: docPage("/docs/mention"),
  order: docPage("/docs/order"),
  object: docPage("/docs/object"),
  tree: docPage("/docs/tree"),
  database: docPage("/docs/database"),
  officialHands: docPage("/docs/official-hands"),
  intent: docPage("/docs/intent"),
  intentGuide: docPage("/docs/intent-guide"),
  api: docPage("/docs/api"),
  jsonDocumentApi: docPage("/docs/api/json-document"),
  selectionApi: docPage("/docs/api/selection"),
  editingApi: docPage("/docs/api/editing"),
  reactApi: docPage("/docs/api/react"),
  reactHookFormApi: docPage("/docs/api/react-hook-form"),
  ajvApi: docPage("/docs/api/ajv"),
  a2uiApi: docPage("/docs/api/a2ui"),
  connectorA2ui: docPage("/docs/connector-a2ui"),
  zodApi: docPage("/docs/api/zod"),
  tanStackTableApi: docPage("/docs/api/tanstack-table"),
  affordanceApi: docPage("/docs/api/affordance"),
  uiPrimitivesApi: docPage("/docs/api/ui-primitives-react"),
  animationApi: docPage("/docs/api/animation-react"),
  markdownReactApi: docPage("/docs/api/markdown-react"),
  databaseApi: docPage("/docs/api/database"),
  annotationApi: docPage("/docs/api/annotation"),
  calendarApi: docPage("/docs/api/calendar"),
  webApi: docPage("/docs/api/web"),
  contenteditableApi: docPage("/docs/api/contenteditable"),
  richTextApi: docPage("/docs/api/rich-text"),
  fileIntakeApi: docPage("/docs/api/file-intake"),
  richTextSuggestionApi: docPage("/docs/api/rich-text-suggestion"),
  richTextSuggestionReactApi: docPage("/docs/api/rich-text-suggestion-react"),
  richTextMentionApi: docPage("/docs/api/rich-text-mention"),
  richTextMentionReactApi: docPage("/docs/api/rich-text-mention-react"),
  composerApi: docPage("/docs/api/composer"),
  composerReactApi: docPage("/docs/api/composer-react"),
  richTextWebApi: docPage("/docs/api/rich-text-web"),
  richTextReactApi: docPage("/docs/api/rich-text-react"),
  collaborationApi: docPage("/docs/api/collaboration"),
  contenteditableCollaborationApi: docPage("/docs/api/contenteditable-collaboration"),
  topology: docPage("/docs/topology"),
  selection: docPage("/docs/selection"),
  history: docPage("/docs/history"),
  clipboard: docPage("/docs/clipboard"),
} as const;

export type DocPageId = keyof typeof docPages;
