export { createJSONDocument } from "./create.js";
export type {
  JSONCapabilityResult,
  JSONDocument,
  JSONDocumentOptions,
} from "./contract.js";
export type {
  JSONDocumentSchemaInput,
  JSONDocumentSchemaLike,
  JSONDocumentSchemaOutput,
} from "./create.js";

export { JSONDocumentError } from "../../domain/document/index.js";
export type {
  HistoryTransactionOptions,
  JSONChangeMetadata,
  JSONDocumentCommitOptions,
  JSONDocumentHistory,
  JSONDocumentSelectionTarget,
} from "../../domain/document/index.js";
export type {
  JSONDocumentDuplicateError,
  JSONDocumentDuplicateOptions,
  JSONDocumentDuplicateResult,
  JSONDocumentEditError,
  JSONDocumentEditOk,
  JSONDocumentEditResult,
  JSONDocumentInsertOptions,
  JSONDocumentInsertTarget,
  JSONDocumentMoveTarget,
} from "../../domain/document/index.js";
export type {
  JSONDocumentPasteOptions,
  JSONDocumentPasteTarget,
  ClipboardCopyOptions,
  ClipboardCopyError,
  ClipboardCopyOk,
  ClipboardCopyResult,
  ClipboardCutOk,
  ClipboardCutError,
  ClipboardCutOptions,
  ClipboardCutResult,
  ClipboardEmpty,
  ClipboardMutationOk,
  ClipboardPasteDiscriminatorMismatch,
  ClipboardPasteError,
  ClipboardPasteResult,
  ClipboardReadOk,
  ClipboardReadOptions,
  ClipboardReadResult,
  ClipboardState,
  ClipboardWriteOptions,
  ClipboardSource,
} from "../../domain/document/index.js";
export type {
  EntriesResult,
  EntryKind,
  QueryResult,
  ReadEntry,
  ReadResult,
} from "../../domain/document/index.js";
export type {
  SchemaDescription,
  SchemaDescriptionResult,
  SchemaErrorCode,
  SchemaErrorResult,
  SchemaKind,
  SchemaKindResult,
  SchemaPathMode,
  SchemaQueryResult,
  SchemaState,
} from "../../domain/document/index.js";
export type {
  SelectionOptions,
  SelectionState,
  SelectionAffinity,
  SelectionContext,
  SelectionCursorDirection,
  SelectionCursorErrorCode,
  SelectionCursorOptions,
  SelectionCursorResult,
  SelectionCursorTarget,
  SelectionDirection,
  SelectionEdge,
  SelectionMode,
  SelectionOrderErrorCode,
  SelectionOrderOptions,
  SelectionOrderedRange,
  SelectionOrderedRangeEntry,
  SelectionPoint,
  SelectionPointObject,
  SelectionPointOrderResult,
  SelectionPointerSpan,
  SelectionPointerSpansResult,
  SelectionRange,
  SelectionRangeInput,
  SelectionRangeOrderResult,
  SelectionRangesOrderResult,
  SelectionScopeErrorCode,
  SelectionScopeOptions,
  SelectionScopeResult,
  SelectionScopeTarget,
  SelectionSnap,
  SelectionSource,
  SelectionSpanOptions,
  SelectionType,
  DeleteSelectionTextResult,
  ReplaceSelectionTextResult,
  SelectionTextDeleteDirection,
  SelectionTextDeleteOptions,
  SelectionTextEdit,
  SelectionTextEditErrorCode,
  SelectionTextEditOptions,
  SelectionTextEditsResult,
} from "../../domain/document/index.js";
export {
  applyOperation,
  applyPatch,
  applyPatchToTrustedState,
} from "../../domain/document/index.js";
export type {
  JSONPatchInput,
  JSONPatchOperation,
  JSONResult,
} from "../../domain/document/index.js";
export {
  parsePointer,
  tryParsePointer,
  buildPointer,
  escapeSegment,
  unescapeSegment,
  PointerSyntaxError,
  parentPointer,
  lastSegment,
  lastSegmentIndex,
  appendSegment,
  withLastSegment,
  resolveSiblingRange,
  trackPointer,
} from "../../domain/document/index.js";
export type {
  Pointer,
  ResolveSiblingRangeOptions,
  SiblingLocation,
  SiblingRangeErrorCode,
  SiblingRangeResult,
} from "../../domain/document/index.js";
export {
  replaceTextSurfaceSelection,
  syncTextSurfaceMutation,
  textSurfaceFragment,
} from "../../domain/document/index.js";
export type {
  TextSurface,
  TextSurfaceAtom,
  TextSurfaceError,
  TextSurfaceErrorCode,
  TextSurfaceFragment,
  TextSurfaceFragmentResult,
  TextSurfaceMutationRange,
  TextSurfaceMutationResult,
  TextSurfaceRange,
  TextSurfaceReplaceOptions,
  TextSurfaceReplaceResult,
  TextSurfaceReplacement,
  TextSurfaceSelectionRange,
} from "../../domain/document/index.js";
